- hosts: localhost
  roles:
    - ansible-role-create-tier1-server

- hosts: just_created
  roles:
    - ansible-role-gen-token

- hosts: webserver
  become: yes
  roles:
    - ansible-role-deploy-site
  tasks:
   - name: Modify site with token
     lineinfile:
       path: "{{ sandbox_folder }}/index.html"
       regex: "VERSION"
       line: "<td>{{ hostvars[hostvars.localhost.ec2.instances[0].public_ip].token.stdout }}</td>"
