---
- hosts: webserver
  vars:
    repo: https://github.com/helozano/ansible-training.git
    repo_folder: /tmp/repo
    html_folder: /var/www/html
    html_file: index.html
  tasks:
   - name: pull repo
     git:
       repo: "{{ repo }}"
       dest: "{{ repo_folder }}"

   - name: Install nginx
     apt:
       name: nginx
       state: present

   - name: Copy index.html to html folder
     copy:
       src: "{{ repo_folder }}/{{ html_file }}"
       dest: "{{ html_folder }}"
