---
- hosts: webserver
  vars:
    repo: https://github.com/helozano/ansible-training.git
    repo_folder: /tmp/repo
    html_folder: /var/www/html
    server_file: server_list.tp
    html_file: index.html
  tasks:
   - name: pull repo
     git:
       repo: "{{ repo }}"
       dest: "{{ repo_folder }}"

   - name: Read server list and save it to variable
     shell: "cat {{ repo_folder }}/{{ server_file }}"
     register: server_list

   - name: Install nginx
     apt:
       name: nginx
       state: present

   - name: Delete html contents
     shell: "rm -rf {{ html_folder }}/*"

   - name: Copy index.html to html folder
     copy:
       src: "{{ repo_folder }}/{{ html_file }}"
       dest: "{{ html_folder }}"

   - name: Define region variable
     set_fact:
       region_1: "{{ server_list.stdout_lines[0] }}"

   - name: Add region to indeex file
     lineinfile:
       path: "{{ html_folder }}/{{ html_file }}"
       state: present
       line: "{{ region_1 }}"
